### ISSUE TITLE
[Info]  英文原文采信的是第几版？ (以及其他一些细节问题)

### ISSUE THREAD

**Issue by shouldsee** [Kivy-CN/MLAPP-CN#10]
@cycleuser @wizardforcel 
我考虑空闲时翻译一些章节， 需要各位suggest：

1.  英文原文采信的是第几版？
     * 网上流传的pdf是2012版的1098页。

1. 对于潜在有歧义的词汇存不存在一个共识？

**Comment by cycleuser** [comment]
repo 里面有一个词汇缩写列表，不过词汇这些如果能有语料库就好了，现在没啥思路，都是随便凑合着～～

**Comment by wizardforcel** [comment]
[机器之心的术语表](https://github.com/jiqizhixin/Artificial-Intelligence-Terminology)

这书好像只有第一版啊

**Comment by shouldsee** [comment]
okay sounds good.

**Comment by lhsfcboy** [comment]
这本书目前只有第一版, 也就是你所说的那个"1098页"版本

**Comment by shouldsee** [comment]
知道了

Sent from my iPhone

On 11 Jun 2018, at 04:45, Mike Hongshuai Luo <notifications@github.com<mailto:notifications@github.com>> wrote:


这本书目前只有第一版, 也就是你所说的那个"1098页"版本
