### ISSUE TITLE
提议:项目文件清理

### ISSUE THREAD

**Issue by lhsfcboy** [Kivy-CN/MLAPP-CN#13]
- 是否考虑删除掉 `Figure` 文件夹和 `MLAPP.png`文件

- 是否考虑将PDF文件汇总至 `PDF` 文件夹下

- 是否考虑将html文件汇总至 `HTML` 文件夹下
  - 需要看html格式的读者, 是从 README.md 的链接中直接跳转的

**Comment by cycleuser** [comment]
Figure是准备提供图件的,MLAPP的那个图片倒是无所谓去留.
PDF和HTML汇总是个好主意!

**Comment by lhsfcboy** [comment]
我的意思是 `Figure` 文件夹里的那些原书中的图表,

**Comment by cycleuser** [comment]
啊,我还是没理解啊没理解~~~ 哈哈哈,单一样本 蛋一样笨~~~

**Comment by lhsfcboy** [comment]
就是那些 `1.1.png` 之类的文件, 不都是原书里的图表嘛, 我记得你说 `本文 ... 不包含任何原文图件。`


还有个`杨丽`, `宗师`,  感觉可以脑补一部电影了.

**Comment by cycleuser** [comment]
目录调整完毕~~
