### ISSUE TITLE
[guideline]对于插图的处理

### ISSUE THREAD

**Issue by shouldsee** [Kivy-CN/MLAPP-CN#15]
目前看似大家直接抛弃插图了？这是出于版权的原因还是偷懒？
@cycleuser @wizardforcel @lhsfcboy

**Comment by lhsfcboy** [comment]
版权原因

**Comment by shouldsee** [comment]
@lhsfcboy  目前是否和版权方有过接洽？

**Comment by lhsfcboy** [comment]
没听 @cycleuser 提过，估计没有吧。

**Comment by cycleuser** [comment]
只是分享笔记,笔记是不需要包括插图的~
所以就这样咯~

**Comment by shouldsee** [comment]
@cycleuser 好
