### ISSUE TITLE
[report]原书中第21章的公式勘误

### ISSUE THREAD

**Issue by shouldsee** [Kivy-CN/MLAPP-CN#17]
## p746, eqn:21.91

应为
$$
\mathbb{E}[ x^2 | x \sim \mathcal{N} (\mu , \sigma^2) ] = \mu^2 + \sigma^2
$$

## p750, eqn:(21.127)

应为
$$
\log q(z) = \sum_k \sum_i z_{ik} \log \rho_{ik} + \text{const}
$$

**Comment by lhsfcboy** [comment]
都看到第21章了啊!!! 牛 

正态分布量的平方的期望确实应该是期望的平法加方差,

**Comment by shouldsee** [comment]
@lhsfcboy 额我是跳着看的，因为最近用混合分布比较多所以顺便翻译一下VBEM。21.5差不多翻译完了21.6还在翻译，适当的时候可以pull一下

**Comment by shouldsee** [comment]
呃麻烦把这些谬误归档一下到error.md

Sent from my iPhone

On 19 Jun 2018, at 01:41, Mike Hongshuai Luo <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #17<https://github.com/Kivy-CN/MLAPP-CN/issues/17>.
