### ISSUE TITLE
第二章的CDF communicative distribution function的意思是连续分布函数，而不是连续密度函数，density

### ISSUE THREAD

**Issue by Clairewr** [Kivy-CN/MLAPP-CN#29]
本项目不支持在线浏览器直接读取，自己clone到本地想办法解决阅读问题。

### Bug report

**错误概述**

**你使用的编辑器/阅读工具**

**错误所在位置**

**其他内容**

<!有其他方面内容在这里填写-->

**Comment by cycleuser** [comment]
OK, 多谢多谢, 已在Markdown文件内更正. 其他文件暂时没办法编辑, 欢迎 PR
